# Generated by Django 4.1.1 on 2022-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_icon', models.ImageField(upload_to='img')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.CharField(max_length=100)),
                ('app_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
            ],
        ),
    ]
